#pragma once

/**
 * @brief Simulation output data associated with a single Reaction Control System (RCS) thruster.
 *
 * This structure represents the scalar thrust state of an individual RCS engine
 * as used inside the propulsion subsystem. The physical thrust vector is not
 * stored directly here. Instead, the thrust magnitude is combined with the
 * engine thrust direction by the Thrust Orchestrator when generating the final
 * spacecraft force vector.
 *
 * This separation allows actuator dynamics and propulsion logic to remain
 * independent from the spacecraft force aggregation layer.
 */
struct RCS_ThrustState
{
    /**
     * @brief Actual scalar thrust magnitude generated by the RCS thruster.
     *
     * Represents the physically generated thrust after command delay,
     * actuator dynamics, and saturation effects have been applied.
     *
     * The corresponding thrust vector is generated externally by combining
     * this scalar magnitude with the engine thrust direction vector.
     *
     * Unit: N
     */
    double currentThrust{0.0};

    /**
     * @brief Commanded scalar thrust magnitude.
     *
     * Represents the desired thrust requested by the controller or user input
     * before actuator dynamics are applied.
     *
     * Unit: N
     */
    double targetThrust{0.0};

    /**
     * @brief Commanded thrust level relative to maximum available thrust.
     *
     * Typical values:
     * - 0.0 = thruster inactive
     * - 1.0 = maximum commanded thrust
     *
     * The BasicRCSModel currently operates as a binary actuator model, therefore
     * only values close to 0 or 1 are expected.
     *
     * Unit: -
     */
    double targetThrustPercentage{0.0};

    /**
     * @brief Internal normalized actuator state.
     *
     * Represents the current dynamic state of the thruster actuator and thrust
     * buildup model.
     *
     * Typical range:
     * - 0.0 = no generated thrust
     * - 1.0 = nominal steady-state thrust
     *
     * Unit: -
     */
    double thrustState{0.0};
};
