/**
 * @file landingview.h
 * @brief 2D visualization widget for lunar landing simulation.
 *
 * This widget renders a simplified side view of the spacecraft,
 * its altitude above ground, and basic thrust visualization.
 */

#ifndef LANDINGVIEW_H
#define LANDINGVIEW_H

#include <QWidget>
#include <QTimer>
#include <spacecraftStateStruct.h>

/**
 * @class LandingView
 * @brief 2D landing visualization widget.
 *
 * LandingView renders a vertical slice of the landing scenario:
 * - ground line
 * - spacecraft representation
 * - altitude scaling
 * - thrust indicator
 *
 * The widget is passive and only visualizes values provided
 * through update functions.
 *
 * Info: Generated by ChatGPT. Edit by gerd-lrt-dev
 */
class LandingView : public QWidget
{
    Q_OBJECT

public:
    /**
     * @brief Constructs a LandingView widget.
     * @param parent Optional parent widget.
     */
    explicit LandingView(QWidget *parent = nullptr);

    // =====================
    // Update Interface
    // =====================

    /**
     * @brief Updates the spacecraft altitude.
     * @param meters Current altitude above ground.
     */
    void setAltitude(double meters);

    /**
     * @brief Updates thrust level.
     * @param percent Thrust percentage [0–100].
     */
    void setThrust(double percent);

    /**
     * @brief Updates hull integrity state.
     * @param intact True if spacecraft is intact.
     */
    void setHullIntact(SpacecraftState spacecraftState_);

protected:
    /**
     * @brief Paints the landing visualization.
     * @param event Paint event.
     */
    void paintEvent(QPaintEvent *event) override;

private:
    // =====================
    // Internal State
    // =====================
    double altitudeMeters = 0.0;   ///< Current altitude
    double thrustPercent = 0.0;    ///< Thrust level
    bool   hullIntact     = true;  ///< Hull status

    // =====================
    // Rendering Helpers
    // =====================
    void drawGround(QPainter &p);
    void drawLander(QPainter &p, const QRect &landerRect);
    void drawThrust(QPainter &p, const QRect &landerRect);
    void drawMotionStripes(QPainter& p, int landerY);

    // =====================
    // Motion stripes animation
    // =====================

    QTimer animationTimer;
    int motionOffset = 0;

};

#endif // LANDINGVIEW_H
